services:
  ollama:
    image: ollama/ollama:latest
    container_name: interview-ollama

    ports:
      - "127.0.0.1:11434:11434"

    volumes:
      - ollama_models:/root/.ollama

    gpus: all


volumes:
  ollama_models:
